-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 19, 2024 at 02:55 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `help_desk`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `admin_id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `date_added` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`admin_id`, `email`, `password`, `date_added`) VALUES
(1, 'admin@gmail.com', 'admin@password', '2024-08-03 19:32:26');

-- --------------------------------------------------------

--
-- Table structure for table `help_desk`
--

CREATE TABLE `help_desk` (
  `help_desk_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `date_created` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `help_desk`
--

INSERT INTO `help_desk` (`help_desk_id`, `name`, `email`, `password`, `date_created`) VALUES
(1, 'Mark Mathew Orogu', 'mark@gmail.com', '1', '2024-08-03 19:51:42');

-- --------------------------------------------------------

--
-- Table structure for table `my_ticket`
--

CREATE TABLE `my_ticket` (
  `my_ticket_id` varchar(255) NOT NULL,
  `student_id` int(255) NOT NULL,
  `fullname` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `subject` varchar(255) NOT NULL,
  `message` varchar(5000) NOT NULL,
  `status` varchar(255) NOT NULL,
  `date_sent` timestamp NOT NULL DEFAULT current_timestamp(),
  `response_message` varchar(5000) DEFAULT NULL,
  `help_desk_id` int(11) NOT NULL,
  `response_date` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `my_ticket`
--

INSERT INTO `my_ticket` (`my_ticket_id`, `student_id`, `fullname`, `email`, `subject`, `message`, `status`, `date_sent`, `response_message`, `help_desk_id`, `response_date`) VALUES
('HD317112', 3, 'James Arikya', 'nur@gmail.com', 'Failed School fees payment', 'fgvjhnkmlfcgvbhjnmkl,ghjk', 'Resolved', '2024-08-05 11:58:02', 'resolved', 1, '2024-08-05 13:39:14'),
('HD321446', 3, 'Shamsudeen Musa', 'Shams@gmail.com', 'Portal logging in ', 'Unable to log into the school portal', 'Pending', '2024-08-05 10:57:16', NULL, 0, NULL),
('HD327002', 3, 'Samaila', 'sammy@gmail.com', 'Result Issue', 'Issue with result', 'Resolved', '2024-08-05 09:49:58', 'Your result has been corrected', 1, '2024-08-05 10:15:22'),
('HD348722', 3, 'Ibrahim Nurudeen Shehu', 'nur@gmail.com', 'Pending payment', 'qwertyuioasdfghjkoxcvbnmsdfghjk', 'Pending', '2024-08-05 12:00:40', NULL, 0, NULL),
('HD350148', 3, 'Ibrahim Nurudeen Shehu', 'nur@gmail.com', 'Pending payment', 'Lrem Ipsum dolar', 'Resolved', '2024-08-03 20:51:26', 'Will soon be resolved, sir', 1, '2024-08-05 09:11:45'),
('HD356116', 3, 'Mark James', 'ibrahimnurudeenshehu@gmail.com', 'Failed School fees payment', 'Note that the vendor folder and the vendor/autoload.php script are generated by Composer; they are not part of PHPMailer.\r\n\r\nIf you want to use XOAUTH2 authentication, you will also need to add a dependency on the league/oauth2-client and appropriate service adapters package in your composer.json, or take a look at by SendOauth2.', 'Resolved', '2024-08-05 09:44:04', 'The payment has been resolved', 1, '2024-08-05 09:46:04'),
('HD411416', 4, 'Nuru Ibro Shehu', 'ibrahimnurudeenshehu@gmail.com', 'Result Issue', 'Result IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult IssueResult Issue', 'Resolved', '2024-08-05 13:46:13', 'Kindly visit your exam officer for any result related issue', 1, '2024-08-05 13:48:14'),
('HD475611', 4, 'Nuru Ibro Shehu', 'ibrahimnurudeenshehu@gmail.com', 'Pending payment', 'sedrcfghjkhjn', 'Resolved', '2024-08-05 13:41:39', 'Resolved', 1, '2024-08-05 13:42:06'),
('HD528168', 5, 'Sam', 'sam2@gmail.com', 'Failed School fees payment', 'sdf', 'Pending', '2024-10-01 13:30:15', NULL, 0, NULL),
('HD530503', 5, 'Sam', 'sam2@gmail.com', 'Pending payment', 'asdfghjkl;', 'Resolved', '2024-10-02 12:18:54', 'dfghjkl;', 1, '2024-10-02 12:20:19');

-- --------------------------------------------------------

--
-- Table structure for table `student`
--

CREATE TABLE `student` (
  `student_id` int(11) NOT NULL,
  `fullname` varchar(255) NOT NULL,
  `matricno` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `date_created` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `student`
--

INSERT INTO `student` (`student_id`, `fullname`, `matricno`, `email`, `password`, `date_created`) VALUES
(3, 'Ibrahim Nurudeen Shehu', '0219047000204', 'nur@gmail.com', '1', '2024-08-03 20:50:31'),
(4, 'Nuru Ibro Shehu', '0219047001194', 'ibrahimnurudeenshehu@gmail.com', '1', '2024-08-05 13:41:03'),
(5, 'Sam', '0001', 'sam2@gmail.com', '1', '2024-10-01 13:17:00');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`admin_id`);

--
-- Indexes for table `help_desk`
--
ALTER TABLE `help_desk`
  ADD PRIMARY KEY (`help_desk_id`);

--
-- Indexes for table `my_ticket`
--
ALTER TABLE `my_ticket`
  ADD PRIMARY KEY (`my_ticket_id`),
  ADD KEY `add my_ticket & student table` (`student_id`);

--
-- Indexes for table `student`
--
ALTER TABLE `student`
  ADD PRIMARY KEY (`student_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `admin_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `help_desk`
--
ALTER TABLE `help_desk`
  MODIFY `help_desk_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `student`
--
ALTER TABLE `student`
  MODIFY `student_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `my_ticket`
--
ALTER TABLE `my_ticket`
  ADD CONSTRAINT `add my_ticket & student table` FOREIGN KEY (`student_id`) REFERENCES `student` (`student_id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
